### ISSUE TITLE
More permissions

### ISSUE THREAD

**Issue by litzinger** [mrtopher/dashEE#1]
This is fantastic! The only thing I'd like to see are more permissions. Right now it looks like each dashboard configuration is on a per member basis. It would be nice to be able, as a super admin, to lock certain widgets to the page for all users. I can see times where I'd need all members to see a specific widget, but they could move it and customize around it, but just can't remove it from the screen, and it would obviously appear on their dashboard the first time they login.

This is definitely going to be installed in all our EE sites. Thanks for sharing.

**Comment by adrienne** [comment]
I'd like to add a +1 to this request!

**Comment by marijana** [comment]
I'd also like to add a +1 to this request!

**Comment by mrtopher** [comment]
Version 1.4 adds "saved layouts" which you can now assign to specific membership groups. Check it out and let me know what you think.

**Comment by adrienne** [comment]
Works great for me! Thanks!

**Comment by marijana** [comment]
Awesome, thnx!
