### ISSUE TITLE
Clashes with "Zoo Flexible Admin" add-on

### ISSUE THREAD

**Issue by mrtopher** [mrtopher/dashEE#10]
dashEE does not work with Zoo Flexible Admin also installed.

Need to append JS from other add-ons to dashEE JS in order for it play well with other add-ons.

**Comment by mrtopher** [comment]
Still appears to be an issue after fix.

**Comment by marc524** [comment]
Yea, I've had similar problems with his addon too. I've requested that Zoo Flex Admin extension be run Priority->9 instead of Priority->1 because I've had issues with ZFA and Zenbu for the same reason. 

The only fix for me is to edit ext.zoo_flexible_admin.php and change the priority on line 48 to 9.

**Comment by mrtopher** [comment]
I'm still not too sure what the solution to this problem is... I've been in touch with the guys from ZFA on Twitter and I thought we were good but it appears to still be an issue.

**Comment by bymayo** [comment]
Is there still no fix for this?

I'd love to be able to run ZFA and Dashee together, but ZFA menu bar doesn't show.

**Comment by mrtopher** [comment]
Ah, thanks for this. I was unsure if it was fixed or not myself as I don't use ZFA.

Are you running the latest EE (2.6.x)?

**Comment by bymayo** [comment]
Yeah running 2.6.1 with latest versions / builds of ZFA and Dashee.

Using Dashee & ZFA together would be amazing. I use both for eCommerce sites I run through EE, and I can show my clients the latest orders / members on the dashboard, but also customise the navigation so they can manage products easier. Bliss.

**Comment by mrtopher** [comment]
I think I have a solution but I don't want to push it without testing.

``` php
    public function crumb_remap()
    {
        $this->_EE->load->model('dashee_model');
        $url = $this->_EE->dashee_model->get_module_url();

        $js = '';

        // If another extension shares the same hook
        if ($this->_EE->extensions->last_call !== FALSE)
        {
            $js = $this->_EE->extensions->last_call;
        }

        $js .= "
            $().ready(function() {          
                $('ul#navigationTabs li.home a').attr('href', '" . htmlspecialchars_decode($url) . "');
                $('#breadCrumb ol li:nth-child(2) a').attr('href', '" . htmlspecialchars_decode($url) . "').html('Dashboard');
                $('#breadCrumb ol').show();
            });
        ";

        return $js;
    }

```

Could you replace the crumb_remap function in the ext.dashee.php file (line 89) with the above and see if that doesn't solve the problem?

**Comment by bymayo** [comment]
Works a charm! Both seem to be working with each other now.

**Comment by mrtopher** [comment]
Great, thanks for the confirmation!
