### ISSUE TITLE
After selecting 2 column layout former width of the columns is retained

### ISSUE THREAD

**Issue by Laisvunas** [mrtopher/dashEE#12]
After selecting 2 column layout former width of the columns is retained leaving empty space to the right of the second column.
It seems that after selecting 2 column layout  css rule
# dashContainer .column {width: 29%;}

should be changed to bigger value, say, to 
# dashContainer .column {width: 45%;}

but the value remains the same causing big blank space to appear.

without changing the width of the colums 2 column layout and 1 column layout is of no value to the user. The point of having 2 columns or 1 column is to place more relevant info into the panel.

**Comment by Laisvunas** [comment]
2 columns layout was not working after istallation of the version 1.4 but after paying with it for some time it soddenly began to work as expected - 2 columns layout without empty space to the left.

**Comment by mrtopher** [comment]
I think this is probably just a cache issue. Since you had the module installed previously with the old version of the CSS, it probably required a hard refresh in order for the new values to come through.
