### ISSUE TITLE
After selecting 2 columns layout when adding new widget PHP error displayed

### ISSUE THREAD

**Issue by Laisvunas** [mrtopher/dashEE#13]
After selecting 2 columns layout when adding new widget PHP error displayed.

To replicate:

1) Load default EE layout

2) Go Settings, select 2 columns and submit

3) Go Widgets click "Add" for some widget

4) See PHP error message

Severity: Notice

Message: Undefined offset: 3

Filename: dashee/mcp.dashee.php

Line Number: 713

**Comment by mrtopher** [comment]
Should be fixed with latest bug fix.
