### ISSUE TITLE
Styling issue: After dragging widgets the first widget in the left column is placed lower than the first in the right column

### ISSUE THREAD

**Issue by Laisvunas** [mrtopher/dashEE#14]
After dragging widgets the first widget in the left column is placed lower than the first in the right column

To replicate:

1) Load default EE layout

2) Drag all widgets from the left column to the center column

3) Drag the back

4) See the widgets in the left column being placed lower than in the center column and in the right column

**Comment by mrtopher** [comment]
Should be fixed with latest.
