### ISSUE TITLE
Doesn't show up for members

### ISSUE THREAD

**Issue by ghost** [mrtopher/dashEE#18]
hi 
im having a problem showing dashEE for members but works correct for superadmins

but for superadmins:
 http://domain.com/cms/system/index.php?S=0&D=cp&C=addons_modules&M=show_module_cp&module=dashee
but if i surf to ' http://domain.com/cms/system/
' then it removes the dashee

members:  isn't working
although i did follow the steps 
"User groups must be given permission to access the “Add-Ons” and “Add-Ons: Modules” sections, as well as the module itself, in order for users other than super-admins to access the module. "
However if i add the url manually 'index.php?S=0&D=cp&C=addons_modules&M=show_module_cp&module=dashee' it does work (still not entirely correctly but it shows dashee)

the breadcrumb doesn't redirect to the correct url either 
for example when i edit a page i get right under the main menu 
SITENAME/Dashboard
Sitename is a link but it doesn't redirect correctly

**Comment by mrtopher** [comment]
That's odd.

What version of EE are you running? Are you using multiple site manager?

**Comment by ghost** [comment]
i'm using Installed: 2.3.0 without multiple site manager.

**Comment by mrtopher** [comment]
This one has me stumped... I can't reproduce the issue you're experiencing. Could I possibly get access to your EE install so I could see whats happening first hand? If so, please send access information to chris@monnat.org.

**Comment by ghost** [comment]
Ok i've sended an email
thanks for looking at it.

**Comment by mrtopher** [comment]
Thanks!

So the strange thing is that I'm not experiencing any issues. I am able to log-in and see dashEE with both sets of credentials you sent me.

However, I did notice that you have Zoo Flexible Admin installed and there is already a known issue with dashEE and ZFA not getting along with each other. I'm wondering if this is another symptom of that issue. 

What browser are you using where you are experiencing problems?

**Comment by ghost** [comment]
I did uninstalled the ZooFlexible but still same problem.
I've used chrome and firefox both give the same results.

Either way both Zooflexible and dashEE give the ultimate solution for client friendly cp.

**Comment by mrtopher** [comment]
I wish I could be of more help, but I am unable to reproduce the issue.

Have you confirmed that your users (accessing the site via other computers) are having the same problem?

**Comment by mrtopher** [comment]
I think I might have found your issue, or maybe part of it. In the process of navigating around EE last night I noticed that the dashEE extension is throwing an error when on the publish pages causing the breadcrumb not to display.

I will look into this and see if I can't correct this weekend.

**Comment by mrtopher** [comment]
I believe this has been resolved.
