### ISSUE TITLE
Not redirecting admins shows php notice

### ISSUE THREAD

**Issue by GDmac** [mrtopher/dashEE#24]
Line 138 in the extension gives a notice / error about undefined index.   https://github.com/mrtopher/dashEE/blob/master/third_party/dashee/ext.dashee.php#L138

Should be:

``` php
// if($u['group_id'] == 1 && $this->settings['redirect_admins'][0] != 'yes') return;
   if($u['group_id'] == 1 && empty($this->settings['redirect_admins'][0])) return;
```

**Comment by mrtopher** [comment]
Updated, thanks.
