### ISSUE TITLE
EE 2.6 Compatible?

### ISSUE THREAD

**Issue by boldyellow** [mrtopher/dashEE#25]
Just letting you know... I installed dashEE with EE 2.6 and when I click on the home icon it goes to a 404 page. The developer log says:

Deprecated function set_variable() called in system/expressionengine/third_party/dashee/mcp.dashee.php on line 89.
Deprecated since 2.6. Use view-><var> = <value>; instead.

**Comment by mrtopher** [comment]
Yep, looks like there are some issues with 2.6.

I hope to look into these soon.

**Comment by mrtopher** [comment]
All issues relating to 2.6.x should be resolved with the release of 1.7.

Let me know if you notice anything else.
