### ISSUE TITLE
Default RSS Widget feed needs to be updated

### ISSUE THREAD

**Issue by john-henry** [mrtopher/dashEE#26]
The older RSS feed from ExpressionEngine is no longer accessible and needs to be updated in the RSS widget from 

```
'url' => 'http://expressionengine.com/feeds/rss/eeblog/',
```

to

```
'url' => 'http://ellislab.com/blog/rss-feed',
```

This is also the cause of the PHP errors when adding widget for first time as there is no method for checking if feed does not exist.

**Comment by mrtopher** [comment]
Thanks for the merge request. Works like a charm now.
