### ISSUE TITLE
php error on login

### ISSUE THREAD

**Issue by interfacecreation** [mrtopher/dashEE#28]
Hi 
I am getting a couple of php errors when hitting the home button. RUnning ee 2.5.5.

A PHP Error was encountered

Severity: Notice

Message: Undefined index: fingerprint

Filename: dashee/ext.dashee.php

Line Number: 155

A PHP Error was encountered

Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at /xxx/base/system/codeigniter/system/core/Exceptions.php:170)

Filename: dashee/ext.dashee.php

Line Number: 159

This also means that after login the control panel is blank and shows this error:

Fatal error: Call to undefined function ee() in /Users/christiangeyer/Sites/base/public_html/third_party/dashee/models/dashee_model.php on line 82

thanks for looking in to this

Christian

**Comment by mrtopher** [comment]
Hi Christian,

You either need to update your EE install to 2.6.x or download an earlier version of the module (https://github.com/mrtopher/dashEE/tags).

**Comment by interfacecreation** [comment]
Cheers!
