### ISSUE TITLE
Function ee() only available on EE 2.6+

### ISSUE THREAD

**Issue by johndwells** [mrtopher/dashEE#30]
I've installed dashEE on EE 2.5.5 and was met with a ton of PHP errors all stemming from a call to the undefined function EE().

ee() was introduced in EE 2.6.0, so perhaps you could simply add a helper function that checks if ee() is defined, and if not define it yourself, then your code can carry on as usual...

Thanks!
John

**Comment by mrtopher** [comment]
Yep, I haven't been placing much emphasis on backward compatibility with older versions of EE. I'll look back and tweak if it's not too much trouble.

**Comment by grovberg** [comment]
Or could you at least update Devot:ee to show 2.6 as the minimum version?

**Comment by mrtopher** [comment]
I have removed references to EE() in the latest which should resolve this issue for now.
