### ISSUE TITLE
admin_session_type config changed to cp_session_type in 2.8+

### ISSUE THREAD

**Issue by leekung** [mrtopher/dashEE#33]
file models/dashee_model.php
    public function get_module_url()
    {
        $s = 0;
        switch($this->_EE->config->item('cp_session_type'))

s always 0 as parameter name changed.

**Comment by mrtopher** [comment]
Thanks for pointing this out. dashEE hasn't been updated in a while because I haven't had the time but I'll see what I can do to get the module updated for the latest EE version.

**Comment by AlexaWebhead** [comment]
I've run into this issue as well. I can't log in to the admin while this module/extension is enabled. I've had to disable it until it's compatible with 2.8+.

**Comment by mrtopher** [comment]
Just pushed an update that incorporates this change. Everything should work now.

Let me know if you notice any other issues.
