### ISSUE TITLE
EE v2.8.1 login issues

### ISSUE THREAD

**Issue by NeoMudaly** [mrtopher/dashEE#34]
Previously, I've run Dashee with EE 2.7 with no hassles at all.  This time, on a fresh 2.8.1 install, I was locked out of admin. I had to go into the database and delete all dashEE files manually in order to login to admin. I'm wondering if anyone has experienced this?

**Comment by mrtopher** [comment]
Hi Neo, yeah dashEE is not 2.8 compatible. I've been meaning to get back to
this project for a while and just haven't had the time.

Hopefully I'll be able to revisit soon.

**Comment by NeoMudaly** [comment]
Thanks for the quick reply - I'll keep an eye on it then. 

Great work you're doing here ^^

**Comment by boldyellow** [comment]
Oh rats, I love dashEE!  It's a brilliant add-on!  Can I help pay for it?  It really improves the CP for our less tech savvy clients... thanks so much for it.

**Comment by eddyfever** [comment]
I'm having troubles to get my EE 2.8.1. to work again, what should i delete more besides? 

exp_dashee_layouts
exp_dashee_members
exp_dashee_member_groups_layouts
exp_dashee_settings

**Comment by boldyellow** [comment]
After dashEE broke my 2.8.1, I edited my config file at this line:

```
$config['allow_extensions'] = 'y';
```

I changed the "y" to "n", then went to the CP and uninstalled dashEE the usual way (in Add-ons > Modules). 

Then I reverted to "y" in the config file.

**Comment by eddyfever** [comment]
Thank you for the tip!

Op 18 apr. 2014, om 14:33 heeft boldyellow notifications@github.com het volgende geschreven:

**Comment by mrtopher** [comment]
Hello All, I was able to spend some time tonight and correct the redirect issues being caused by the new CP URLs in EE 2.8.x. Everything should be working as expected now.

Let me know if you notice any other issues.
