### ISSUE TITLE
Fatal error after updating to dashEE 2.0

### ISSUE THREAD

**Issue by jamiepaul** [mrtopher/dashEE#35]
I was previously running dashEE 1.9 and updated to 2.0. Upon going to dashEE from the  Add-Ons > Modules, I get:
"Fatal error: Call to undefined function cp_url() in /workspace/key-surgical/system/expressionengine/third_party/dashee/views/index.php on line 6"

After updating returned the error, I uninstalled and completely removed dashEE's files and made sure the tables were out of the database before installing dashEE 2.0 again. The same error appears.

Environment Details:
- EE v2.7.3 (can update to 2.8.1 if necessary) 
- MAMP Pro (v2.1.1)
- PHP 5.4.4
- Focus Lab config

dashEE 1.9 was a lifesaver for me, thanks for all that you do! Let me know if I can provide any more information.

**Comment by mrtopher** [comment]
Oops, I know exactly whats going on. Will try to address and push an update tonight.

Upgrading EE to 2.8 or later will resolve the problem but I'll push a fix for earlier versions tonight.

**Comment by mrtopher** [comment]
Just pushed an update that should resolve this issue.

Let me know if you run in to any other problems.
