### ISSUE TITLE
Submit new widgets

### ISSUE THREAD

**Issue by reinos** [mrtopher/dashEE#36]
Hi there,

is there a way to add new widgets to your list of widgets? The entry_api also support, as from version 3.4 Dashee with a widget of the latest logs.

Let me know.

Best,
Rein

**Comment by mrtopher** [comment]
Yes, looks like my form got lost in the doc migration over to Github. If you visit the link below you should be able to submit your widget. Then I'll take a quick peak and it should be displayed on the list.

https://mrtopher.wufoo.com/forms/add-your-dashee-widget/
