### ISSUE TITLE
Making possible to have 2 or 3 columns of widgets

### ISSUE THREAD

**Issue by Laisvunas** [mrtopher/dashEE#4]
Currently it is possible to have only 3 columns of widgets. Because columns are 3, widgets are necessarily narrow. 

Narrow widgets isn't good in case some widget should contain rich information. For example, my add-ons New Entries Info http://devot-ee.com/add-ons/new-entries-info or Member Profile Antispam http://devot-ee.com/add-ons/profile-antispam. Yet another example is Google Analytics Panel http://devot-ee.com/add-ons/google-analytics-panel. They look good in EE1.x because CP widgets in EE1.x being sorted into 2 columns are wider; it is difficult to squeeze all that info into narrow space and because of this these and other widgets hardly can be ported to dashEE. 

So, I propose to add an option to have either 2 or 3 columns (i.e. either narrower or wider) widgets.

**Comment by mrtopher** [comment]
I agree. Was debating this right up until release and it didn't make it in. I'll re-prioritize and see what I can do.

CM

**Comment by mrtopher** [comment]
Users can now choose 1, 2 or 3 column layouts for the dashboard.
