### ISSUE TITLE
models/dashee_update_model.php missing in 2.1 zip

### ISSUE THREAD

**Issue by KeesTM** [mrtopher/dashEE#43]
system/expressionengine/third_party/dashee/models/dashee_update_model.php is missing in 2.1 zip on the github page

**Comment by mrtopher** [comment]
I just downloaded it from the releases page (https://github.com/mrtopher/dashEE/releases) and the file is there. Is this where you're downloaded it from?

**Comment by KeesTM** [comment]
ok it doesnt matter. i ended up copying it from another project and it
worked.

Groet,
Jelle de Jong

[image: KeesTM Internetbureau]
http://www.kees-tm.nl/?utm_source=handtekening+kees&utm_medium=e-mail&utm_campaign=handtekening
- Middelstegracht 89s
- 2322 TT Leiden
- 071 - 51 333 71

Volg Kees op[image: g+] https://plus.google.com/109003357537029607371/
[image: f] https://www.facebook.com/keestm
[image: w]
http://www.kees-tm.nl/?utm_source=handtekening+kees&utm_medium=e-mail&utm_campaign=handtekening

2014-12-01 19:07 GMT+01:00 Chris Monnat notifications@github.com:
