### ISSUE TITLE
Simpler way to avoid flashing of the default links before being replaced with the new ones

### ISSUE THREAD

**Issue by Laisvunas** [mrtopher/dashEE#6]
In "Tips & Tricks" part of the docs you recomment to add CSS rule #breadCrumb ol { display:none; } to EE theme override.css file.

There is easier way to achieve the same: using the hook cp_css_end which adds custom CSS to every Control Panel page (see description at )http://expressionengine.com/user_guide/development/extension_hooks/cp/css/index.html

You just need to add cp_css_end to the hooks list in ext.dashee.php file and a simple function:

function cp_css_end()
 {
   $css = "#breadCrumb ol { display:none; }";
   return $css;
 }

**Comment by mrtopher** [comment]
Brilliant!! I'll get this added straight away.
